### ISSUE TITLE
Please provide hibernate5 support.

### ISSUE THREAD

**Issue by ptahchiev** [hazelcast/hazelcast-hibernate4#2]
Hi guys, when I run my server with hibernate5 I get this exception:
````
Caused by: java.lang.AbstractMethodError: com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory.start(Lorg/hibernate/boot/spi/SessionFactoryOptions;Ljava/util/Properties;)V
	at org.hibernate.internal.CacheImpl.<init>(CacheImpl.java:48)
	at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:28)
	at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:20)
	at org.hibernate.service.internal.SessionFactoryServiceRegistryImpl.initiateService(SessionFactoryServiceRegistryImpl.java:46)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:234)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:208)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:189)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:237)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:445)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:779)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:343)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:318)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
	... 94 more

````

**Comment by gochev** [comment]
Indeed we have to use hibernate 4 or ehcache as hazelcast replacement with hibernate 5 until Hazelcast provide support for hibernate 5.
It is a bit weird it doesn't work out of the box I would not expected huge changes in Hibernate 5.

**Comment by kobalski** [comment]
@ptahchiev @gochev  Unfortunately, we do not support hibernate5 right now. The exception you are getting is because of broken backward compatibility of 2nd Level Cache SPI between hibernate 4 and 5. Apparently, in hibernate 5 `RegionCache` interface's start method signature changed. (http://docs.jboss.org/hibernate/orm/5.0/javadocs/org/hibernate/cache/spi/RegionFactory.html). AFAIK hibernate5 has no stable version right now, in future we can provide hibernate 5 support. You can move this issue under hazelcast repo (https://github.com/hazelcast/hazelcast/issues/new). This repo is not the active development repo of hazelcast-hibernate. Hibernate4 integration module is moved here (https://github.com/hazelcast/hazelcast/tree/master/hazelcast-hibernate).

**Comment by mesutcelik** [comment]
This repo is simply dead. I have created an issue on hazelcast repo so feel free updating there.
https://github.com/hazelcast/hazelcast/issues/5640
