### ISSUE TITLE
hazelcast-hibernate4 doesn't work at all

### ISSUE THREAD

**Issue by rmannibucau** [hazelcast/hazelcast-hibernate4#3]
typeId used by the project are < 0 and it is forbidden by hazelcast since versions (at least 3.5)

would it be possible to fix it and at least add a test ensuring this module works?

**Comment by GeorgiKhomeriki** [comment]
This is the exception that I'm getting with hazelcast-hibernate4 version 3.5 and above.

```
Caused by: java.lang.IllegalArgumentException: Type id must be positive! Current: -203, Serializer: com.hazelcast.hibernate.serialization.Hibernate42CacheEntrySerializer@40316fc8
        at com.hazelcast.nio.serialization.SerializationServiceImpl.register(SerializationServiceImpl.java:416)
        at com.hazelcast.nio.serialization.DefaultSerializationServiceBuilder.registerSerializerHooks(DefaultSerializationServiceBuilder.java:245)
        at com.hazelcast.nio.serialization.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:196)
        at com.hazelcast.instance.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:113)
        at com.hazelcast.instance.Node.<init>(Node.java:160)
        at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:120)
        at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:152)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:135)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:111)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
        at com.hazelcast.hibernate.instance.HazelcastInstanceLoader.createOrGetInstance(HazelcastInstanceLoader.java:91)
        at com.hazelcast.hibernate.instance.HazelcastInstanceLoader.loadInstance(HazelcastInstanceLoader.java:81)
        at com.hazelcast.hibernate.AbstractHazelcastCacheRegionFactory.start(AbstractHazelcastCacheRegionFactory.java:88)
        at org.hibernate.internal.CacheImpl.<init>(CacheImpl.java:70)
        at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:40)
        at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:35)
        at org.hibernate.service.internal.SessionFactoryServiceRegistryImpl.initiateService(SessionFactoryServiceRegistryImpl.java:91)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:201)
        ... 32 more
```

**Comment by rmannibucau** [comment]
Seems another user got it http://stackoverflow.com/questions/32637634/hazelcast-hibernate-spring-in-payara-glassfish-environment-type-id-must-be

**Comment by jcetkov** [comment]
this repo is outdated, however this can be reproduced in the current version of hazelcast-hibernate4. The root cause is the hazelcast-hibernate4 being loaded in different classloader than hazelcast jar. In such case the hazelcast-hibernate4 serializers are not recognized as "internal" which causes this exception.

https://github.com/hazelcast/hazelcast/blob/1e1e6751ccc6a8d429315fe0d5e4e4ad9c7196e9/hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/DefaultSerializationServiceBuilder.java#L293
https://github.com/hazelcast/hazelcast/blob/95dcb01d8779801708de9bb8439e8d2bf817df86/hazelcast/src/main/java/com/hazelcast/nio/ClassLoaderUtil.java#L164

**Comment by emre-aydin** [comment]
@rmannibucau @GeorgiKhomeriki @rmannibucau @jcetkov 
I have created a new issue for this on [the official repository of Hazelcast Hibernate plugin repository](https://github.com/hazelcast/hazelcast-hibernate/issues/31) Please follow the progress on this issue there and make sure you open new issues related to Hazelcast Hibernate plugin there.
